CREATE TABLE "DS3_USERDATA"."FT_CELLULAR_DATA_FILES" 
   (	
    "DESCRIPTION" VARCHAR2(200 BYTE), 
	"BATCH_ID" VARCHAR2(20 BYTE), 
	"FILENAME" VARCHAR2(200 BYTE), 
    "EXPERIMENT_DESCRIPTION" VARCHAR2(500 BYTE) NOT NULL ENABLE,
    "ASSAY_TYPE" VARCHAR2(20 BYTE),
	"DOC" VARCHAR2(20 BYTE), 
    "EXTENSION" VARCHAR2(10 BYTE),
	"DOC_ID" VARCHAR2(100 BYTE), 
	"SCRIPT_ID" NUMBER(15,5), 
	"EXPERIMENT_ID" NUMBER(15,5),
    "ISID" VARCHAR2(50 BYTE),
    "ADDED_DATE" DATE NOT NULL ENABLE,
    "MOD_DATE" DATE NOT NULL ENABLE,
	"CRO" VARCHAR2(50 BYTE), 
	"PROJECT" VARCHAR2(10 BYTE), 
	"AUDIT_ID" NUMBER, 
	 FOREIGN KEY ("AUDIT_ID")
	  REFERENCES "DS3_USERDATA"."TM_DATA_UPLOAD_AUDIT" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  GRANT DELETE ON "DS3_USERDATA"."FT_CELLULAR_DATA_FILES" TO "DS3_APPDATA";
  GRANT INSERT ON "DS3_USERDATA"."FT_CELLULAR_DATA_FILES" TO "DS3_APPDATA";
  GRANT SELECT ON "DS3_USERDATA"."FT_CELLULAR_DATA_FILES" TO "DS3_APPDATA";
  GRANT UPDATE ON "DS3_USERDATA"."FT_CELLULAR_DATA_FILES" TO "DS3_APPDATA";
