SET SERVEROUTPUT ON;

--CREATE TABLE COPY_KINASE_PANEL AS SELECT * FROM FT_KINASE_PANEL; 
--DROP TABLE COPY_KINASE_PANEL;

DECLARE
    TMP_TECH VARCHAR2(255);--FT_KINASE_PANEL.TECHNOLOGY%TYPE;
    CURSOR c_cursor
    IS 
        SELECT 
            TECHNOLOGY 
        FROM FT_KINASE_PANEL
        FOR UPDATE;
BEGIN
    dbms_output.put_line('Program started.');
    FOR r_val IN c_cursor
    LOOP
        CASE
            WHEN (r_val.TECHNOLOGY IN ('HotSpot', 'Hotspot')) THEN TMP_TECH := 'Hot Spot';
            WHEN (r_val.TECHNOLOGY IN ('Adapta', 'adapta')) THEN TMP_TECH := 'ADAPTA';
            WHEN r_val.TECHNOLOGY = 'radiometric' THEN TMP_TECH := 'Radiometric';
            WHEN r_val.TECHNOLOGY = 'Lantha_screen' THEN TMP_TECH := 'Lantha Screen';
            ELSE TMP_TECH := r_val.TECHNOLOGY;
            --DBMS_OUTPUT.PUT_LINE('OLD: ' || r_val.TECHNOLOGY || '| NEW: ' ||TMP_TECH);
        END CASE;
        UPDATE FT_KINASE_PANEL 
           SET TECHNOLOGY = TMP_TECH
         WHERE CURRENT OF c_cursor;
    END LOOP;
END;
/



SELECT DISTINCT TECHNOLOGY FROM DS3_USERDATA.FT_KINASE_PANEL;
SELECT DISTINCT TECHNOLOGY FROM DS3_USERDATA.COPY_KINASE_PANEL;

SELECT TECHNOLOGY, COUNT(TECHNOLOGY) FROM FT_KINASE_PANEL GROUP BY TECHNOLOGY;
SELECT TECHNOLOGY, COUNT(TECHNOLOGY) FROM COPY_KINASE_PANEL GROUP BY TECHNOLOGY;