select * from FT_PHARM_EFFICACY_RAW;



ALTER TABLE FT_PHARM_EFFICACY_RAW ADD (
    BW_G_NUMBER NUMBER,
    L_MM_NUMBER NUMBER,
    W_MM_NUMBER NUMBER,
    TV_MM_3_NUMBER NUMBER
);



UPDATE FT_PHARM_EFFICACY_RAW SET
    BW_G_NUMBER = TO_NUMBER(BW_G),
    L_MM_NUMBER = TO_NUMBER(L_MM),
    W_MM_NUMBER = TO_NUMBER(W_MM),
    TV_MM_3_NUMBER = TO_NUMBER(TV_MM_3);
    

ALTER TABLE FT_PHARM_EFFICACY_RAW DROP COLUMN BW_G;
ALTER TABLE FT_PHARM_EFFICACY_RAW DROP COLUMN L_MM;
ALTER TABLE FT_PHARM_EFFICACY_RAW DROP COLUMN W_MM;
ALTER TABLE FT_PHARM_EFFICACY_RAW DROP COLUMN TV_MM_3;


ALTER TABLE FT_PHARM_EFFICACY_RAW RENAME COLUMN BW_G_NUMBER TO BW_G;
ALTER TABLE FT_PHARM_EFFICACY_RAW RENAME COLUMN L_MM_NUMBER TO L_MM;
ALTER TABLE FT_PHARM_EFFICACY_RAW RENAME COLUMN W_MM_NUMBER TO W_MM;
ALTER TABLE FT_PHARM_EFFICACY_RAW RENAME COLUMN TV_MM_3_NUMBER TO TV_MM_3;



select TV_MM_3_NUMBER from FT_PHARM_EFFICACY_RAW;



select * from ft_pharm_study;