--------------------------------------------------------

DROP TABLE "DS3_USERDATA"."FT_PHARM_EFFICACY_RAW";

--------------------------------------------------------
--  DDL for Table FT_PHARM_RAW
--------------------------------------------------------

  CREATE TABLE "DS3_USERDATA"."FT_PHARM_EFFICACY_RAW" 
   (	
    "SAMPLE_ID" VARCHAR2(20 BYTE),
    "ANIMAL_ID" VARCHAR2(20 BYTE),
    "SAMPLING_TIME" DATE,
    "BW_G" VARCHAR2(20 BYTE), 
    "L_MM" VARCHAR2(20 BYTE),
    "W_MM" VARCHAR2(20 BYTE),
    "TV_MM_3" VARCHAR2(20 BYTE),
    "OBSERVATION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "DS3_USERDATA"."FT_PHARM_EFFICACY_RAW"."OBSERVATION" IS 'clinical obs';