select MAX("ClosestSMILES") from FOUNT.CALCULATED_FT_VK_QSAR_MODELS t1 WHERE REGNO = 'FT000016' AND PROJECT_NAME='KIN-01' AND peyn_comment='CDK12' AND "BestSimilarity" = (
    SELECT MAX("BestSimilarity") FROM FOUNT.CALCULATED_FT_VK_QSAR_MODELS t1 WHERE REGNO = 'FT000016' AND PROJECT_NAME='KIN-01' AND peyn_comment='CDK12'
    );


select DISTINCT
    FIRST_VALUE("ClosestSMILES") OVER ( ORDER BY "BestSimilarity" DESC)
from FOUNT.CALCULATED_FT_VK_QSAR_MODELS WHERE REGNO = 'FT000016' AND PROJECT_NAME='KIN-01' AND peyn_comment='CDK12' ;


SELECT MAX("BestSimilarity") FROM FOUNT.CALCULATED_FT_VK_QSAR_MODELS t1 WHERE REGNO = 'FT000016' AND PROJECT_NAME='KIN-01' AND peyn_comment='CDK12';


SELECT AVG("QSAR_Model") OVER ( ORDER BY "BestSimilarity" DESC)
from FOUNT.CALCULATED_FT_VK_QSAR_MODELS WHERE REGNO = 'FT000016' AND PROJECT_NAME='KIN-01' AND peyn_comment='CDK12' ;

